# Configuration preprocessor
constants: {}
---

general:
  logger:
    log-level: warning
    file: $$$MW_TRACE_DIRECTORY$$$/log.txt
  monitor:
    enable: true
    sample-rate: 50
    
testcase:
  module: load
  module-options:
    input-directory: $$$MW_TESTCASE_DIRECTORY$$$
    
trace:
  module: load
  module-options:
    input-directory: $$$MW_TRACE_DIRECTORY$$$
  options:
    input-buffer-size: 5
    
preprocess:
  module: js
  module-options:
    output-directory: $$$MW_TRACE_DIRECTORY$$$
    map-directory: $$$MW_MAPS_DIRECTORY$$$
    store-traces: true
  options:
    input-buffer-size: 4
    max-parallel-threads: 4
  
analysis:
  modules:
    - module: passthrough
  options:
    input-buffer-size: 4
    max-parallel-threads: 1
